### ISSUE TITLE
Blackboard is not sending https://purl.imsglobal.org/spec/lti/claim/resource_link claim

### ISSUE THREAD

**Issue by mwleinad** [1EdTech/lti-1-3-php-library#43]
https://github.com/IMSGlobal/lti-1-3-php-library/blob/master/src/lti/message_validators/resource_message_validator.php#L20

Blackboard made a change from 3800.2 to 3800.4 and now they do not send this claim for some launches.

I notice that you throw an error if the claim is not there. AFAIK this claim is required, right?

Would there be any case where the claim is not present in an LTI 1.3 launch?
Is Blackboard failing to comply with the 1.3 standard?

I'm forking on this library so for now I will just comment out that line, but I wonder if I'm introducing new errors/security concerns?

Thanks!

**Comment by MartinLenord** [comment]
The resource link claim isn't required for deep linking launches (because the resource does not exist at that point) if the message type is LtiResourceLinkRequest then it is required

**Comment by mwleinad** [comment]
Yeah, this is not a deep linking launch

**Comment by MartinLenord** [comment]
How is the tool placement configured? @ewpreston may be able to shed more light on this

**Comment by ewpreston** [comment]
We fixed a bug in 3800.4 around this. The first release of 3800.4 to partners had the issue, but we fixed it before we released to production.

From where are you launching and what type of LTI placement is it? Course, Content, System, or Admin?

If you launch it from the Content Market by clicking on the icon we don't send the resource link claim, because it is not associated with a resource at that point.

While the spec says it is "required" that's because 10 years ago when LTI first came out the only option was a link associated with a resource. Now Learn lets you launch from many places, some of which are not associated with a resource, so tools should be able to handle that.

I will change the code however, to always send a resource_link claim with a random number for the ID, since the spec says it is required, and tools choke when they don't receive it
